version: '3.8'

services:
  api:
    container_name: spring-boot-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: emanuelmachado1983/car-dealearship-offices-docker:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8082
    command: java -jar /app/target/*.jar
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 50s
      timeout: 10s
      retries: 5
      start_period: 40s