name: Maven Package build Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean compile -DskipTests -B package --file pom.xml
      
  test:
    runs-on: ubuntu-latest
    needs: build   # Wait for the build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Execute tests
        run: mvn clean test

  package:
    runs-on: ubuntu-latest
    needs: test   # Wait for test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Package project
        run: mvn package -B --file pom.xml

  docker:
    runs-on: ubuntu-latest
    needs: package   # Wait for package
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Docker
        run: docker build -t emanuelmachado1983/car-dealearship-offices-docker:${{ github.sha }} .

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_API_PASSWORD }}

      - name: Push Docker
        run: docker push emanuelmachado1983/car-dealearship-offices-docker:${{ github.sha }}

  deploy-render:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Trigger Render Deploy
        run: |
          DEPLOY_URL="${{ secrets.RENDER_DEPLOY_HOOK_URL }}&imgURL=docker.io%2Femanuelmachado1983%2Fcar-dealearship-offices-docker%3A${{ github.sha }}"
          curl -X POST "$DEPLOY_URL"

